version: 2
jobs:
  build:
    working_directory: ~/proconist.net
    docker:
      - image: circleci/ruby:2.5.1-stretch-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - proconist-middleman-{{ checksum "Gemfile.lock" }}
            - proconist-middleman
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: proconist-middleman-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec middleman build
  deploy:
    working_directory: ~/proconist.net
    docker:
      - image: circleci/ruby:2.5.1-stretch-node-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c9:8a:53:1a:c2:d7:ce:70:9c:88:8c:19:32:1b:57:7d"
      - checkout
      - restore_cache:
          keys:
            - proconist-middleman-{{ checksum "Gemfile.lock" }}
            - proconist-middleman-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: proconist-middleman-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: git config --global user.name "circleci"
      - run: git config --global user.email "sayhi@circleci.com"
      - run: bundle exec middleman deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
