version: 2
jobs:
  build:
    working_directory: ~/proconist.net
    docker:
      - image: circleci/ruby:2.5.1-stretch-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - proconist-rails-{{ checksum "Gemfile.lock" }}
            - proconist-rails-
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: proconist-rails-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec middleman build
