AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'sinatra/**/*'
    - 'vendor/**/*'
    - 'db/**/*'

Rails:
  Enabled:  true

Lint/MissingCopEnableDirective:
  Enabled: false

Metrics/LineLength:
  Max: 130

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/ExtraSpacing:
  Exclude:
    - 'config/routes.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19

Style/IfUnlessModifier:
  Enabled: false

Style/Next:
  Exclude:
    - 'lib/scripts/*'

Style/StringLiterals:
 EnforcedStyle: single_quotes

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
